"""empty message

Revision ID: 198ba0bcb6e5
Revises: cb4c1ce80e47
Create Date: 2021-01-27 20:37:30.017155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198ba0bcb6e5'
down_revision = 'cb4c1ce80e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'num_upcoming_shows')
    # ### end Alembic commands ###
